In [94]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [95]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df = application_df.drop(['EIN','NAME'], axis=1)
application_df.head()

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [96]:
# Determine the number of unique values in each column.
print(application_df.nunique())

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [97]:
# Look at APPLICATION_TYPE value counts for binning
counts_apptype = application_df['APPLICATION_TYPE'].value_counts()
counts_apptype

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [98]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
application_types_to_replace = list(counts_apptype[counts_apptype<5].index)

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
T9         156
T13         66
T12         27
T2          16
Other       11
Name: APPLICATION_TYPE, dtype: int64

In [99]:
# Look at CLASSIFICATION value counts for binning
class_counts = application_df['CLASSIFICATION'].value_counts()
class_counts

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [100]:
# You may find it helpful to look at CLASSIFICATION value counts >1
f_c_counts = class_counts[class_counts > 1]
f_c_counts

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: CLASSIFICATION, dtype: int64

In [101]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
cutoff_value = 500
classifications_to_replace = []

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [102]:
# Convert categorical data to numeric with `pd.get_dummies`
application_df = pd.get_dummies(application_df)
application_df.head()

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T12,APPLICATION_TYPE_T13,APPLICATION_TYPE_T19,APPLICATION_TYPE_T2,APPLICATION_TYPE_T3,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,1,108590,1,0,0,0,0,0,0,1,...,1,0,0,0,0,0,0,0,1,0
2,1,5000,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
3,1,6692,1,0,0,0,0,0,0,1,...,0,1,0,0,0,0,0,0,1,0
4,1,142590,1,0,0,0,0,0,0,1,...,0,0,1,0,0,0,0,0,1,0

In [103]:
# Split our preprocessed data into our features and target arrays
y = application_df['IS_SUCCESSFUL'].values


# drop SUCCESSFUL
X = application_df.drop('IS_SUCCESSFUL', axis=1).values

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X,y,random_state = 42)

# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [129]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
input_feats = len(X_train_scaled[0])
nn_model = tf.keras.models.Sequential()

# First hidden layer
nn_model.add(tf.keras.layers.Dense(units=7, activation='relu', input_dim=input_feats))

# Second hidden layer
nn_model.add(tf.keras.layers.Dense(units=14, activation='relu'))

# Third hidden layer
nn_model.add(tf.keras.layers.Dense(units=21, activation='relu'))

# Fourth Layer
#nn_model.add(tf.keras.layers.Dense(units=16, activation='relu'))
# Output layer
nn_model.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

# Check the structure of the model
nn_model.summary()

Model: "sequential_8"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_38 (Dense)            (None, 7)                 791

 dense_39 (Dense)            (None, 14)                112

 dense_40 (Dense)            (None, 21)                315

 dense_41 (Dense)            (None, 1)                 22

=================================================================
Total params: 1240 (4.84 KB)
Trainable params: 1240 (4.84 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [130]:
# Compile the model
optimizer = tf.keras.optimizers.Adam(learning_rate=0.0001)
nn_model.compile(optimizer=optimizer, loss='binary_crossentropy', metrics=['accuracy'])

# Train the model
early_stopping = tf.keras.callbacks.EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)
#class_weights = {0: 1, 1: 2}
fit_model = nn_model.fit(X_train_scaled, y_train, validation_split=0.15, epochs=100, batch_size=64, callbacks=[early_stopping])

Epoch 1/100
342/342 [==============================] - 2s 3ms/step - loss: 0.7061 - accuracy: 0.5166 - val_loss: 0.6846 - val_accuracy: 0.5864
Epoch 2/100
342/342 [==============================] - 1s 3ms/step - loss: 0.6747 - accuracy: 0.5973 - val_loss: 0.6602 - val_accuracy: 0.6893
Epoch 3/100
342/342 [==============================] - 1s 2ms/step - loss: 0.6482 - accuracy: 0.6917 - val_loss: 0.6371 - val_accuracy: 0.7103
Epoch 4/100
342/342 [==============================] - 1s 2ms/step - loss: 0.6290 - accuracy: 0.7094 - val_loss: 0.6199 - val_accuracy: 0.7227
Epoch 5/100
342/342 [==============================] - 1s 3ms/step - loss: 0.6148 - accuracy: 0.7147 - val_loss: 0.6076 - val_accuracy: 0.7261
Epoch 6/100
342/342 [==============================] - 1s 4ms/step - loss: 0.6049 - accuracy: 0.7155 - val_loss: 0.5984 - val_accuracy: 0.7264
Epoch 7/100
342/342 [==============================] - 1s 3ms/step - loss: 0.5968 - accuracy: 0.7167 - val_loss: 0.5903 - val_accuracy: 0.7269
Epoch 8/100
342/342 [==============================] - 1s 2ms/step - loss: 0.5899 - accuracy: 0.7198 - val_loss: 0.5837 - val_accuracy: 0.7326
Epoch 9/100
342/342 [==============================] - 1s 2ms/step - loss: 0.5843 - accuracy: 0.7214 - val_loss: 0.5789 - val_accuracy: 0.7328
Epoch 10/100
342/342 [==============================] - 1s 2ms/step - loss: 0.5798 - accuracy: 0.7225 - val_loss: 0.5750 - val_accuracy: 0.7328
Epoch 11/100
342/342 [==============================] - 1s 2ms/step - loss: 0.5763 - accuracy: 0.7232 - val_loss: 0.5721 - val_accuracy: 0.7326
Epoch 12/100
342/342 [==============================] - 1s 2ms/step - loss: 0.5732 - accuracy: 0.7228 - val_loss: 0.5690 - val_accuracy: 0.7326
Epoch 13/100
342/342 [==============================] - 1s 2ms/step - loss: 0.5705 - accuracy: 0.7225 - val_loss: 0.5665 - val_accuracy: 0.7310
Epoch 14/100
342/342 [==============================] - 1s 2ms/step - loss: 0.5682 - accuracy: 0.7223 - val_loss: 0.5645 - val_accuracy: 0.7323
Epoch 15/100
342/342 [==============================] - 1s 3ms/step - loss: 0.5663 - accuracy: 0.7237 - val_loss: 0.5627 - val_accuracy: 0.7349
Epoch 16/100
342/342 [==============================] - 1s 2ms/step - loss: 0.5646 - accuracy: 0.7250 - val_loss: 0.5615 - val_accuracy: 0.7341
Epoch 17/100
342/342 [==============================] - 1s 2ms/step - loss: 0.5632 - accuracy: 0.7268 - val_loss: 0.5603 - val_accuracy: 0.7341
Epoch 18/100
342/342 [==============================] - 1s 3ms/step - loss: 0.5620 - accuracy: 0.7270 - val_loss: 0.5591 - val_accuracy: 0.7346
Epoch 19/100
342/342 [==============================] - 1s 2ms/step - loss: 0.5608 - accuracy: 0.7274 - val_loss: 0.5582 - val_accuracy: 0.7349
Epoch 20/100
342/342 [==============================] - 1s 4ms/step - loss: 0.5598 - accuracy: 0.7271 - val_loss: 0.5573 - val_accuracy: 0.7354
Epoch 21/100
342/342 [==============================] - 1s 3ms/step - loss: 0.5588 - accuracy: 0.7276 - val_loss: 0.5567 - val_accuracy: 0.7354
Epoch 22/100
342/342 [==============================] - 1s 3ms/step - loss: 0.5580 - accuracy: 0.7275 - val_loss: 0.5561 - val_accuracy: 0.7352
Epoch 23/100
342/342 [==============================] - 1s 4ms/step - loss: 0.5573 - accuracy: 0.7278 - val_loss: 0.5555 - val_accuracy: 0.7354
Epoch 24/100
342/342 [==============================] - 1s 3ms/step - loss: 0.5565 - accuracy: 0.7281 - val_loss: 0.5550 - val_accuracy: 0.7359
Epoch 25/100
342/342 [==============================] - 1s 2ms/step - loss: 0.5559 - accuracy: 0.7278 - val_loss: 0.5546 - val_accuracy: 0.7359
Epoch 26/100
342/342 [==============================] - 1s 2ms/step - loss: 0.5553 - accuracy: 0.7282 - val_loss: 0.5542 - val_accuracy: 0.7365
Epoch 27/100
342/342 [==============================] - 1s 3ms/step - loss: 0.5547 - accuracy: 0.7282 - val_loss: 0.5537 - val_accuracy: 0.7359
Epoch 28/100
342/342 [==============================] - 1s 2ms/step - loss: 0.5542 - accuracy: 0.7288 - val_loss: 0.5535 - val_accuracy: 0.7362
Epoch 29/100
342/342 [==============================] - 1s 2ms/step - loss: 0.5537 - accuracy: 0.7289 - val_loss: 0.5535 - val_accuracy: 0.7354
Epoch 30/100
342/342 [==============================] - 1s 2ms/step - loss: 0.5532 - accuracy: 0.7297 - val_loss: 0.5531 - val_accuracy: 0.7354
Epoch 31/100
342/342 [==============================] - 1s 2ms/step - loss: 0.5529 - accuracy: 0.7294 - val_loss: 0.5529 - val_accuracy: 0.7357
Epoch 32/100
342/342 [==============================] - 1s 2ms/step - loss: 0.5525 - accuracy: 0.7295 - val_loss: 0.5527 - val_accuracy: 0.7357
Epoch 33/100
342/342 [==============================] - 1s 3ms/step - loss: 0.5522 - accuracy: 0.7298 - val_loss: 0.5525 - val_accuracy: 0.7359
Epoch 34/100
342/342 [==============================] - 1s 4ms/step - loss: 0.5519 - accuracy: 0.7298 - val_loss: 0.5525 - val_accuracy: 0.7362
Epoch 35/100
342/342 [==============================] - 1s 3ms/step - loss: 0.5515 - accuracy: 0.7299 - val_loss: 0.5522 - val_accuracy: 0.7359
Epoch 36/100
342/342 [==============================] - 1s 2ms/step - loss: 0.5512 - accuracy: 0.7307 - val_loss: 0.5520 - val_accuracy: 0.7357
Epoch 37/100
342/342 [==============================] - 1s 2ms/step - loss: 0.5510 - accuracy: 0.7305 - val_loss: 0.5521 - val_accuracy: 0.7359
Epoch 38/100
342/342 [==============================] - 1s 2ms/step - loss: 0.5507 - accuracy: 0.7308 - val_loss: 0.5520 - val_accuracy: 0.7357
Epoch 39/100
342/342 [==============================] - 1s 3ms/step - loss: 0.5505 - accuracy: 0.7307 - val_loss: 0.5521 - val_accuracy: 0.7357
Epoch 40/100
342/342 [==============================] - 1s 2ms/step - loss: 0.5502 - accuracy: 0.7306 - val_loss: 0.5522 - val_accuracy: 0.7357
Epoch 41/100
342/342 [==============================] - 1s 2ms/step - loss: 0.5500 - accuracy: 0.7308 - val_loss: 0.5521 - val_accuracy: 0.7357
Epoch 42/100
342/342 [==============================] - 1s 3ms/step - loss: 0.5497 - accuracy: 0.7308 - val_loss: 0.5520 - val_accuracy: 0.7357
Epoch 43/100
342/342 [==============================] - 1s 4ms/step - loss: 0.5497 - accuracy: 0.7314 - val_loss: 0.5518 - val_accuracy: 0.7365
Epoch 44/100
342/342 [==============================] - 1s 4ms/step - loss: 0.5494 - accuracy: 0.7316 - val_loss: 0.5518 - val_accuracy: 0.7362
Epoch 45/100
342/342 [==============================] - 1s 2ms/step - loss: 0.5493 - accuracy: 0.7316 - val_loss: 0.5519 - val_accuracy: 0.7362
Epoch 46/100
342/342 [==============================] - 1s 3ms/step - loss: 0.5491 - accuracy: 0.7316 - val_loss: 0.5518 - val_accuracy: 0.7365
Epoch 47/100
342/342 [==============================] - 1s 4ms/step - loss: 0.5489 - accuracy: 0.7316 - val_loss: 0.5519 - val_accuracy: 0.7365
Epoch 48/100
342/342 [==============================] - 1s 4ms/step - loss: 0.5487 - accuracy: 0.7317 - val_loss: 0.5521 - val_accuracy: 0.7365
Epoch 49/100
342/342 [==============================] - 1s 3ms/step - loss: 0.5486 - accuracy: 0.7312 - val_loss: 0.5519 - val_accuracy: 0.7354
Epoch 50/100
342/342 [==============================] - 1s 2ms/step - loss: 0.5484 - accuracy: 0.7314 - val_loss: 0.5519 - val_accuracy: 0.7352
Epoch 51/100
342/342 [==============================] - 1s 2ms/step - loss: 0.5483 - accuracy: 0.7318 - val_loss: 0.5518 - val_accuracy: 0.7359
Epoch 52/100
342/342 [==============================] - 1s 2ms/step - loss: 0.5481 - accuracy: 0.7317 - val_loss: 0.5517 - val_accuracy: 0.7359
Epoch 53/100
342/342 [==============================] - 1s 3ms/step - loss: 0.5479 - accuracy: 0.7321 - val_loss: 0.5518 - val_accuracy: 0.7359
Epoch 54/100
342/342 [==============================] - 1s 3ms/step - loss: 0.5478 - accuracy: 0.7318 - val_loss: 0.5519 - val_accuracy: 0.7357
Epoch 55/100
342/342 [==============================] - 1s 2ms/step - loss: 0.5476 - accuracy: 0.7317 - val_loss: 0.5520 - val_accuracy: 0.7359
Epoch 56/100
342/342 [==============================] - 1s 3ms/step - loss: 0.5475 - accuracy: 0.7317 - val_loss: 0.5519 - val_accuracy: 0.7357
Epoch 57/100
342/342 [==============================] - 1s 3ms/step - loss: 0.5474 - accuracy: 0.7317 - val_loss: 0.5518 - val_accuracy: 0.7357
Epoch 58/100
342/342 [==============================] - 1s 3ms/step - loss: 0.5473 - accuracy: 0.7317 - val_loss: 0.5518 - val_accuracy: 0.7359
Epoch 59/100
342/342 [==============================] - 1s 2ms/step - loss: 0.5472 - accuracy: 0.7315 - val_loss: 0.5518 - val_accuracy: 0.7357
Epoch 60/100
342/342 [==============================] - 1s 3ms/step - loss: 0.5470 - accuracy: 0.7316 - val_loss: 0.5517 - val_accuracy: 0.7357
Epoch 61/100
342/342 [==============================] - 1s 3ms/step - loss: 0.5469 - accuracy: 0.7322 - val_loss: 0.5516 - val_accuracy: 0.7354
Epoch 62/100
342/342 [==============================] - 1s 4ms/step - loss: 0.5468 - accuracy: 0.7319 - val_loss: 0.5518 - val_accuracy: 0.7357
Epoch 63/100
342/342 [==============================] - 1s 2ms/step - loss: 0.5466 - accuracy: 0.7321 - val_loss: 0.5519 - val_accuracy: 0.7354
Epoch 64/100
342/342 [==============================] - 1s 2ms/step - loss: 0.5466 - accuracy: 0.7322 - val_loss: 0.5518 - val_accuracy: 0.7357
Epoch 65/100
342/342 [==============================] - 1s 2ms/step - loss: 0.5465 - accuracy: 0.7321 - val_loss: 0.5516 - val_accuracy: 0.7359
Epoch 66/100
342/342 [==============================] - 1s 3ms/step - loss: 0.5463 - accuracy: 0.7320 - val_loss: 0.5516 - val_accuracy: 0.7357
Epoch 67/100
342/342 [==============================] - 1s 2ms/step - loss: 0.5463 - accuracy: 0.7319 - val_loss: 0.5519 - val_accuracy: 0.7365
Epoch 68/100
342/342 [==============================] - 1s 2ms/step - loss: 0.5461 - accuracy: 0.7319 - val_loss: 0.5520 - val_accuracy: 0.7367
Epoch 69/100
342/342 [==============================] - 1s 2ms/step - loss: 0.5461 - accuracy: 0.7324 - val_loss: 0.5519 - val_accuracy: 0.7357
Epoch 70/100
342/342 [==============================] - 1s 2ms/step - loss: 0.5460 - accuracy: 0.7318 - val_loss: 0.5519 - val_accuracy: 0.7365
Epoch 71/100
342/342 [==============================] - 1s 3ms/step - loss: 0.5458 - accuracy: 0.7324 - val_loss: 0.5520 - val_accuracy: 0.7357
Epoch 72/100
342/342 [==============================] - 1s 3ms/step - loss: 0.5457 - accuracy: 0.7324 - val_loss: 0.5521 - val_accuracy: 0.7372
Epoch 73/100
342/342 [==============================] - 1s 3ms/step - loss: 0.5457 - accuracy: 0.7328 - val_loss: 0.5522 - val_accuracy: 0.7346
Epoch 74/100
342/342 [==============================] - 1s 3ms/step - loss: 0.5456 - accuracy: 0.7328 - val_loss: 0.5522 - val_accuracy: 0.7370
Epoch 75/100
342/342 [==============================] - 1s 3ms/step - loss: 0.5456 - accuracy: 0.7328 - val_loss: 0.5522 - val_accuracy: 0.7370
Epoch 76/100
342/342 [==============================] - 1s 3ms/step - loss: 0.5454 - accuracy: 0.7330 - val_loss: 0.5522 - val_accuracy: 0.7365

In [131]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn_model.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 0.5568 - accuracy: 0.7276 - 338ms/epoch - 1ms/step
Loss: 0.5568108558654785, Accuracy: 0.727580189704895

In [ ]:
# Export our model to HDF5 file